version: '3.7'

services:
  app:
    container_name: highres_seg_demo
    build: .
    command: 'gunicorn -b 0.0.0.0:8075 --reload app:server'
    environment:
      TILED_URI: '${TILED_URI}'
      API_KEY: '${API_KEY}'
    ports:
      - '8075:8075'
